### ISSUE TITLE
`dfuzzer --lis` seems to crash :-)

### ISSUE THREAD

**Issue by evverx** [systemd/systemd-dfuzzer#5]
```sh
Program received signal SIGSEGV, Segmentation fault.
__strncmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:115
115		vmovdqu	(%rdi), %ymm1
(gdb) bt
#0  __strncmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:115
#1  0x00007ffff7b213a1 in process_long_option
    (argc=argc@entry=2, argv=argv@entry=0x7fffffffe288, optstring=optstring@entry=0x40917d "n:o:i:m:b:t:e:L:sdvlhV", longopts=longopts@entry=0x40aa00 <options>, longind=longind@entry=0x0, long_only=0, d=0x7ffff7c2dc80 <getopt_data>, print_errors=1, prefix=0x7ffff7be996c "--") at getopt.c:212
#2  0x00007ffff7b21d87 in _getopt_internal_r
    (argc=argc@entry=2, argv=argv@entry=0x7fffffffe288, optstring=optstring@entry=0x40917d "n:o:i:m:b:t:e:L:sdvlhV", longopts=longopts@entry=0x40aa00 <options>, longind=longind@entry=0x0, long_only=long_only@entry=0, d=0x7ffff7c2dc80 <getopt_data>, posixly_correct=0) at getopt.c:650
#3  0x00007ffff7b21ff5 in _getopt_internal
    (argc=argc@entry=2, argv=argv@entry=0x7fffffffe288, optstring=optstring@entry=0x40917d "n:o:i:m:b:t:e:L:sdvlhV", longopts=longopts@entry=0x40aa00 <options>, longind=longind@entry=0x0, long_only=long_only@entry=0, posixly_correct=0) at getopt.c:711
#4  0x00007ffff7b22082 in getopt_long
    (argc=argc@entry=2, argv=argv@entry=0x7fffffffe288, options=options@entry=0x40917d "n:o:i:m:b:t:e:L:sdvlhV", long_options=long_options@entry=0x40aa00 <options>, opt_index=opt_index@entry=0x0)
    at getopt1.c:31
#5  0x0000000000404227 in df_parse_parameters (argc=2, argv=0x7fffffffe288) at dfuzzer.c:1098
#6  0x0000000000402512 in main (argc=<optimized out>, argv=<optimized out>) at dfuzzer.c:98
```

**Comment by evverx** [comment]
My bad. I missed that. I'll open a PR with
```diff
diff --git a/src/dfuzzer.c b/src/dfuzzer.c
index 1725eb7..4459568 100644
--- a/src/dfuzzer.c
+++ b/src/dfuzzer.c
@@ -1093,6 +1093,7 @@ void df_parse_parameters(int argc, char **argv)
                { "verbose",                    no_argument,            NULL,   'v' },
                { "log-dir",                    required_argument,      NULL,   'L' },
                { "version",                    no_argument,            NULL,   'V' },
+               {}
        };

        while ((c = getopt_long(argc, argv, "n:o:i:m:b:t:e:L:sdvlhV", options, NULL)) >= 0) {
```

**Comment by mrc0mmand** [comment]
Oh god, thanks for catching that :facepalm:
